<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>

    <!-- Don't warn about "This package may not be fully compatible with your project" due to using netstandard2.1 but using packages that only target net framework -->
     <NoWarn>$(NoWarn);NU1701</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../AudioStreamer/AudioStreamer.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1"/>
  </ItemGroup>
</Project>
